language: node_js
dist: trusty
node_js:
  - lts/*
cache:
  directories:
    - node_modules
script:
  - npm run build
  - cd ./dist/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master